mod android;
mod minecraft;
mod po;

use std::{
    borrow::Cow,
    collections::{HashMap, HashSet},
    fmt::{self, Debug, Formatter},
    sync::Arc,
    vec,
};

use async_trait::async_trait;
use reqwest::Client;
use unic_langid::LanguageIdentifier;

pub use self::{android::AndroidHttpProvider, minecraft::MinecraftProvider, po::PoHttpProvider};
use super::Translation;

#[async_trait]
pub trait TranslationProvider {
    fn id(&self) -> &str;

    fn name(&self) -> &str;

    fn group_name(&self) -> Option<&str> {
        None
    }

    async fn generate(
        &self,
        lang_ids: Vec<LanguageIdentifier>,
        client: &Client,
    ) -> Result<HashMap<LanguageIdentifier, Option<Vec<Translation>>>, anyhow::Error>;
}

impl Debug for dyn TranslationProvider + Send + Sync {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "provider({})", self.id())
    }
}

macro_rules! gnome {
    ($name:literal, $repo:literal) => {
        gnome!($name, "GNOME", $repo)
    };
    ($name:literal, $category:literal, $repo:literal) => {
        Arc::new(PoHttpProvider {
            id: Cow::Borrowed($repo),
            name: $name,
            group_name: Some("GNOME"),
            check_url: Cow::Borrowed(concat!(
                "https://gitlab.gnome.org/",
                $category,
                "/",
                $repo,
                "/-/tree/master/po/"
            )),
            url: |lang_id| {
                format!(
                    concat!(
                        "https://gitlab.gnome.org/",
                        $category,
                        "/",
                        $repo,
                        "/-/raw/master/po/{}.po"
                    ),
                    lang_id.language.as_str()
                )
            },
            remove_char: '_',
        })
    };
}

macro_rules! kde {
    ($name:literal, $category:literal) => {{
        let repo = str::to_lowercase($name);
        kde!(
            $name,
            $category,
            Cow::<'static, str>::Owned(repo.clone()),
            "po",
            repo
        )
    }};
    ($name:literal, $category:literal > $file_name:literal) => {
        kde!(
            $name,
            $category,
            Cow::<'static, str>::Owned(str::to_lowercase($name)),
            "po",
            $file_name
        )
    };
    ($name:literal, $category:literal, $repo:literal > $file_name:literal) => {
        kde!(
            $name,
            $category,
            Cow::<'static, str>::Borrowed($repo),
            "po",
            $file_name
        )
    };
    ($name:literal, $category:literal > $folder:literal, $file_name:literal) => {
        kde!(
            $name,
            $category,
            Cow::<'static, str>::Owned(str::to_lowercase($name)),
            $folder,
            $file_name
        )
    };
    ($name:literal, $category:literal, $repo:literal > $folder:literal, $file_name:literal) => {
        kde!(
            $name,
            $category,
            Cow::<'static, str>::Borrowed($repo),
            $folder,
            $file_name
        )
    };
    ($name:literal, $category:literal, $repo:expr, $folder:literal, $file_name:expr) => {
        Arc::new(PoHttpProvider {
            id: $repo,
            name: $name,
            group_name: Some("KDE"),
            check_url: Cow::Owned(format!(
                concat!(
                    "https://invent.kde.org/",
                    $category,
                    "/{0}/-/tree/master/",
                    $folder,
                ),
                $repo,
            )),
            url: move |lang_id| {
                format!(
                    concat!(
                        "https://invent.kde.org/",
                        $category,
                        "/{0}/-/raw/master/",
                        $folder,
                        "/{1}/{2}.po",
                    ),
                    $repo,
                    lang_id.language.as_str(),
                    $file_name,
                )
            },
            remove_char: '&',
        })
    };
}

macro_rules! android {
    ($name:literal, $repo:literal, $folder:literal) => {
        Arc::new(AndroidHttpProvider {
            id: concat!($repo, "/", $folder),
            name: $name,
            group_name: Some("Android"),
            default_url: concat!(
                "https://android.googlesource.com/platform/",
                $repo,
                "/+/master/",
                $folder,
                "/values/strings.xml?format=TEXT",
            ),
            url: |lang_id| {
                format!(
                    concat!(
                        "https://android.googlesource.com/platform/",
                        $repo,
                        "/+/master/",
                        $folder,
                        "/values-{}/strings.xml?format=TEXT",
                    ),
                    lang_id.language.as_str()
                )
            },
        })
    };
}

#[rustfmt::skip]
pub fn default_providers() -> Vec<Arc<dyn TranslationProvider + Send + Sync>> {
    let providers: Vec<Arc<dyn TranslationProvider + Send + Sync>> = vec![
        Arc::new(MinecraftProvider),

        kde!("KMag",       "accessibility"),
        kde!("KMouseTool", "accessibility"),
        kde!("KMouth",     "accessibility"),
        kde!("Kontrast",   "accessibility"),
        kde!("Artikulate",         "education"),
        kde!("Blinken",            "education"),
        kde!("Cantor",             "education"),
        kde!("GCompris",           "education"),
        kde!("KAlgebra",           "education"),
        kde!("Kalzium",            "education"),
        kde!("Kanagram",           "education"),
        kde!("KBruch",             "education"),
        kde!("KGeography",         "education"),
        kde!("KHangMan",           "education"),
        kde!("Khipu",              "education"),
        kde!("Kig",                "education"),
        kde!("Kiten",              "education"),
        kde!("KLettres",           "education"),
        kde!("MkPlot",             "education"),
        kde!("KStars",             "education"),
        kde!("KTouch",             "education"),
        kde!("KTurtle",            "education"),
        kde!("KWordQuiz",          "education"),
        kde!("LapPlot",            "education"),
        kde!("libkeduvocdocument", "education"),
        kde!("Marble",             "education"),
        kde!("Minuet",             "education"),
        kde!("Parley",             "education"),
        kde!("RKWard",             "education"),
        kde!("Rocs",               "education"),
        kde!("Step",               "education"),
        kde!("Baloo",                       "frameworks"),
        kde!("KArchive",                    "frameworks"                         > "poqm", "karchive6_qt"),
        kde!("KAuth",                       "frameworks"                         > "poqm", "kauth6_qt"),
        kde!("KBookmarks",                  "frameworks"                         > "poqm", "kbookmarks6_qt"),
        kde!("KCMUtils",                    "frameworks"),
        kde!("KCodecs",                     "frameworks"                         > "poqm", "kcodecs6_qt"),
        kde!("KColorScheme",                "frameworks"),
        kde!("KCompletion",                 "frameworks"                         > "poqm", "kcompletion6_qt"),
        kde!("KConfig",                     "frameworks"                         > "poqm", "kconfig6_qt"),
        kde!("KConfigWidgets",              "frameworks"),
        kde!("KCoreAddons",                 "frameworks"                         > "poqm", "kcoreaddons6_qt"),
        kde!("KDav",                        "frameworks"),
        kde!("KDBusAddons",                 "frameworks"                         > "poqm", "kdbusaddons6_qt"),
        kde!("KDE4 Support",                "frameworks", "kdelibs4support"      > "po",   "kdelibs4support"),
        kde!("KDeclerative",                "frameworks"),
        kde!("KDE Plasma Framework",        "frameworks", "plasma-framework"     >         "libplasma6"),
        kde!("KDesignerPlugin",             "frameworks"                         > "poqm", "kdesignerplugin5_qt"),
        kde!("KDE Su",                      "frameworks", "kdesu"                > "po",   "kdesud6"),
        kde!("KDNSSD Framework",            "frameworks", "kdnssd"               > "poqm", "kdnssd6_qt"),
        kde!("KDocTools",                   "frameworks"                         >         "kdoctools6"),
        kde!("KFileMetadata",               "frameworks"                         >         "kfilemetadata6"),
        kde!("KGlobalAccel",                "frameworks"                         > "poqm", "kglobalaccel6_qt"),
        kde!("kholidays",                   "frameworks"                         > "poqm", "libkholidays6_qt"),
        kde!("KHtml",                       "frameworks"                         >         "khtml5"),
        kde!("KI18n",                       "frameworks"                         >         "ki18n6"),
        kde!("KIconThemes",                 "frameworks"                         >         "kiconthemes6"),
        kde!("KInit",                       "frameworks"                         >         "kinit5"),
        kde!("KIO",                         "frameworks"                         >         "kio6"),
        kde!("Kirigami",                    "frameworks"                         >         "libkirigami6_qt"),
        kde!("KItemViews",                  "frameworks"                         >         "kitemviews6_qt"),
        kde!("KJobWidgets",                 "frameworks"                         > "poqm", "kjobwidgets6_qt"),
        kde!("KJSEmbed",                    "frameworks"                         >         "kjsembed5"),
        kde!("KNewStuff",                   "frameworks"                         >         "knewstuff6"),
        kde!("KNotifications",              "frameworks"                         > "poqm", "knotifications6_qt"),
        kde!("KParts",                      "frameworks"                         >         "kparts6"),
        kde!("KPeople",                     "frameworks"                         >         "kparts6"),
        kde!("KPty",                        "frameworks"                         >         "kpty6"),
        kde!("Kross",                       "frameworks"                         >         "kross5"),
        kde!("KService",                    "frameworks"                         >         "kservice6"),
        kde!("KStatusNotifierItem",         "frameworks"                         > "poqm", "kstatusnotifieritem6_qt"),
        kde!("KSVG",                        "frameworks"                         >         "libksvg6"),
        kde!("KTextEditor",                 "frameworks"                         >         "ktexteditor6"),
        kde!("KTextWidgets",                "frameworks"                         >         "ktextwidgets6"),
        kde!("KUnitConversion",             "frameworks"                         >         "kunitconversion6"),
        kde!("KWallet Framework",           "frameworks", "kwallet"              > "po",   "kwalletd6"),
        kde!("KWallet Framework query",     "frameworks", "kwallet"              > "po",   "kwallet6-query"),
        kde!("KWidgetsAddons",              "frameworks"                         > "poqm", "kwidgetsaddons6_qt"),
        kde!("KWindowSystem",               "frameworks"                         > "poqm", "kwindowsystem6_qt"),
        kde!("KXMLGUI",                     "frameworks"                         >         "kxmlgui6"),
        kde!("kxmlrpcclient",               "frameworks"                         >         "libkxmlrpcclient5"),
        kde!("Package framework",           "frameworks", "kpackage"             > "po",   "libkpackage6"),
        kde!("Sonnet",                      "frameworks"                         > "poqm", "sonnet6_qt"),
        kde!("Syntax Highlightning Engine", "frameworks", "syntax-highlightning" > "poqm", "syntaxhighlighting6_qt"),
        kde!("Purpose framework quick",            "frameworks", "purpose"       > "po",   "libpurpose6_quick"),
        kde!("Purpose framework widgets",          "frameworks", "purpose"       > "po",   "libpurpose6_widgets"),
        kde!("Purpose framework barcode",          "frameworks", "purpose"       > "po",   "purpose6_barcode"),
        kde!("Purpose framework bluetooth",        "frameworks", "purpose"       > "po",   "purpose6_bluetooth"),
        kde!("Purpose framework file item action", "frameworks", "purpose"       > "po",   "purpose6_fileitemaction"),
        kde!("Purpose framework Imgur",            "frameworks", "purpose"       > "po",   "purpose6_imgur"),
        kde!("Purpose framework KDE Connect",      "frameworks", "purpose"       > "po",   "purpose6_kdeconnect"),
        kde!("Purpose framework KDE Connect SMS",  "frameworks", "purpose"       > "po",   "purpose6_kdeconnectsms"),
        kde!("Purpose framework NextCloud",        "frameworks", "purpose"       > "po",   "purpose6_nextcloud"),
        kde!("Purpose framework Pastebin",         "frameworks", "purpose"       > "po",   "purpose6_pastebin"),
        kde!("Purpose framework Phabricator",      "frameworks", "purpose"       > "po",   "purpose6_phabricator"),
        kde!("Purpose framework ReviewBoard",      "frameworks", "purpose"       > "po",   "purpose6_reviewboard"),
        kde!("Purpose framework save as",          "frameworks", "purpose"       > "po",   "purpose6_saveas"),
        kde!("Purpose framework YouTube",          "frameworks", "purpose"       > "po",   "purpose6_youtube"),
        kde!("Amor",              "games"),
        kde!("Atlantik",          "games"),
        kde!("Bomber",            "games"),
        kde!("Bovo",              "games"),
        kde!("Granatier",         "games"),
        kde!("Kajongg",           "games"),
        kde!("Kapman",            "games"),
        kde!("Katonic",           "games"),
        kde!("KBlackBox",         "games"),
        kde!("KBlocks",           "games"),
        kde!("KBounce",           "games"),
        kde!("KBreakOut",         "games"),
        kde!("KDiamond",          "games"),
        kde!("KFourInLine",       "games"),
        kde!("KGoldrunner",       "games"),
        kde!("Kigo",              "games"),
        kde!("Killbots",          "games"),
        kde!("Kiriki",            "games"),
        kde!("KJumpingCube",      "games"),
        kde!("Klickety",          "games"),
        kde!("KLines",            "games"),
        kde!("KMahjongg",         "games"),
        kde!("KMines",            "games"),
        kde!("KMuddy",            "games"),
        kde!("KNavalBattle",      "games"),
        kde!("KNetWalk",          "games"),
        kde!("Knights",           "games"),
        kde!("Kolf",              "games"),
        kde!("Kollision",         "games"),
        kde!("Kolorfill",         "games" > "poqm", "kolorfill_qt"),
        kde!("Konquest",          "games"),
        kde!("KPat",              "games"),
        kde!("KReversi",          "games"),
        kde!("KShisen",           "games"),
        kde!("KsirK",             "games"),
        kde!("KsirK skin editor", "games" > "ksirkskineditor"),
        kde!("KSnakeDuel",        "games"),
        kde!("KSpaceDuel",        "games"),
        kde!("KSquares",          "games"),
        kde!("KSudoku",           "games"),
        kde!("KTuberling",        "games"),
        kde!("Kubrick",           "games"),
        kde!("libkdegames",       "games" > "libkdegames6"),
        kde!("libkmahjongg",      "games" > "libkmahjongg6"),
        kde!("Lieutenant Skat",   "games" > "lskat"),
        kde!("Palapeli",          "games"),
        kde!("Picmi",             "games"),
        kde!("Skladnik",          "games"),
        kde!("Arianna",           "graphics"),
        kde!("colord-kde",        "graphics"),
        kde!("digiKam",           "graphics"),
        kde!("Gwenview",          "graphics"),
        kde!("Kamera",            "graphics" > "kcmkamera"),
        kde!("Kamera",            "graphics" > "kio5_kamera"),
        kde!("KColorChooser",     "graphics"),
        kde!("KDiagram",          "graphics" > "poqm", "kchart_qt"),
        kde!("KDiagram",          "graphics" > "poqm", "kgantt_qt"),
        kde!("KGeoTag",           "graphics"),
        kde!("KGraphViewer",      "graphics"),
        kde!("KImageMap Editor",  "graphics" > "kimagemapeditor"),
        kde!("Kipi Plugins",                "graphics" > "kipiplugins"),
        kde!("Kipi Plugin Dropbox",         "graphics" > "kipiplugin_dropbox"),
        kde!("Kipi Plugin Facebook",        "graphics" > "kipiplugin_facebook"),
        kde!("Kipi Plugin Flickr",          "graphics" > "kipiplugin_flickr"),
        kde!("Kipi Plugin Google services", "graphics" > "kipiplugin_googleservices"),
        kde!("Kipi Plugin ImageShack",      "graphics" > "kipiplugin_imageshack"),
        kde!("Kipi Plugin Imgur",           "graphics" > "kipiplugin_imgur"),
        kde!("Kipi Plugin jAlbum",          "graphics" > "kipiplugin_jalbum"),
        kde!("Kipi Plugin KML export",      "graphics" > "kipiplugin_kmlexport"),
        kde!("Kipi Plugin MediaWiki",       "graphics" > "kipiplugin_mediawiki"),
        kde!("Kipi Plugin Piwigo",          "graphics" > "kipiplugin_piwigo"),
        kde!("Kipi Plugin print images",    "graphics" > "kipiplugin_printimages"),
        kde!("Kipi Plugin Rajce",           "graphics" > "kipiplugin_rajce"),
        kde!("Kipi Plugin remote storage",  "graphics" > "kipiplugin_remotestorage"),
        kde!("Kipi Plugin send images",     "graphics" > "kipiplugin_sendimages"),
        kde!("Kipi Plugin Smug",            "graphics" > "kipiplugin_smug"),
        kde!("Kipi Plugin Yandex fotki",    "graphics" > "kipiplugin_yandexfotki"),
        kde!("Kodaskanna",       "graphics"),
        kde!("Koko",             "graphics"),
        kde!("KolorManager",     "graphics" > "kmdevices"),
        kde!("KolorManager",     "graphics" > "kminfo"),
        kde!("KolorManager",     "graphics" > "kmservices"),
        kde!("KolourPaint",      "graphics"),
        kde!("Kooka",            "graphics"),
        kde!("Kooka",            "graphics" > "libkookascan"),
        kde!("KPhotoAlbum",      "graphics"),
        kde!("Krita",            "graphics"),
        kde!("KRuler",           "graphics"),
        kde!("Kuickshow",        "graphics"),
        kde!("KXStitch",         "graphics"),
        kde!("libksane",         "graphics"),
        kde!("Okular",           "graphics" > "okular"),
        kde!("Okular",           "graphics" > "okular_chm"),
        kde!("Okular",           "graphics" > "okular_comicbook"),
        kde!("Okular",           "graphics" > "okular_djvu"),
        kde!("Okular",           "graphics" > "okular_dvi"),
        kde!("Okular",           "graphics" > "okular_epub"),
        kde!("Okular",           "graphics" > "okular_fax"),
        kde!("Okular",           "graphics" > "okular_fictionbook"),
        kde!("Okular",           "graphics" > "okular_ghostview"),
        kde!("Okular",           "graphics" > "okular_kimgio"),
        kde!("Okular",           "graphics" > "okular_mobi"),
        kde!("Okular",           "graphics" > "okular_plucker"),
        kde!("Okular",           "graphics" > "okular_poppler"),
        kde!("Okular",           "graphics" > "okular_txt"),
        kde!("Okular",           "graphics" > "okular_xps"),
        kde!("Okular",           "graphics" > "org.kde.active.documentviewer"),
        kde!("Peruse",           "graphics"),
        kde!("Pikasso",          "graphics"),
        kde!("PVfViewer",        "graphics" > "pvfViewer"),
        kde!("SeExpr for Krita", "graphics", "kseexpr" > "seexpr2_qt"),
        kde!("Skanlite",         "graphics"),
        kde!("Spectacle",        "graphics"),
        kde!("SVG KPart",        "graphics" > "svgpart"),
        kde!("SymbolEditor",     "graphics" > "SymbolEditor"),
        kde!("KDevelop",                         "kdevelop"),
        kde!("KDevelop CSS Support",             "kdevelop", "kdev-css"            > "kdevcss"),
        kde!("KDevelop Embedded Support",        "kdevelop", "kdev-embedded"       > "kdevembedded"),
        kde!("KDevelop Execute Browser Support", "kdevelop", "kdev-executebrowser" > "kdevexecutebrowser"),
        kde!("KDevelop Krazy2 Support",          "kdevelop", "kdev-krazy2"         > "kdevkrazy2"),
        kde!("KDevelop Mercurial Support",       "kdevelop", "kdev-mercurial"      > "kdevmercurial"),
        kde!("KDevelop PHP Support",             "kdevelop", "kdev-php"            > "kdevphp"),
        kde!("KDevelop Python Support",          "kdevelop", "kdev-python"         > "kdevpython"),
        kde!("KDevelop Ruby Support",            "kdevelop", "kdev-ruby"           > "kdevruby"),
        kde!("KDevelop Upload Plugin",           "kdevelop", "kdev-upload"         > "kdevupload"),
        kde!("KDevelop Valgrind Support",        "kdevelop", "kdev-valgrind"       > "kdevvalgrind"),
        kde!("KDevelop Verapp Support",          "kdevelop", "kdev-verapp"         > "kdevverapp"),
        kde!("KDevelop XDebug Support",          "kdevelop", "kdev-xdebug"         > "kdevxdebug"),
        kde!("AtCore",                     "libraries"                    > "poqm", "atcore_qt"),
        kde!("Baloo Widgets",              "libraries", "baloo-widgets"   >         "baloowidgets5"),
        kde!("KDb",                        "libraries"                    > "poqm", "kdb_qt"),
        kde!("KDb MySQL driver",           "libraries", "kdb"             > "poqm", "kdb_mysqldriver_qt"),
        kde!("KDb PostgreSQL driver",      "libraries", "kdb"             > "poqm", "kdb_postgresqldriver_qt"),
        kde!("KDb SQLite driver",          "libraries", "kdb"             > "poqm", "kdb_sqlitedriver_qt"),
        kde!("Kirigami Add-ons",           "libraries", "kirigami-addons" >         "kirigami-addons6"),
        kde!("KMoreTools",                 "libraries"                    >         "kmoretools6"),
        kde!("KOpeningHours",              "libraries"),
        kde!("KOSMIndoorMap",              "libraries"),
        kde!("KProperty",                  "libraries"                    > "poqm", "kpropertycore_qt"),
        kde!("KProperty widgets",          "libraries", "kproperty"       > "poqm", "kpropertywidgets_qt"),
        kde!("KReport",                    "libraries"                    > "poqm", "kreport_qt"),
        kde!("KSANECore",                  "libraries"                    >         "ksanecore"),
        kde!("KTextAddons widgets",        "libraries", "ktextaddons"     >         "libtextaddonswidgets"),
        kde!("KTextAddons autocorrection", "libraries", "ktextaddons"     >         "libtextautocorrection"),
        kde!("KTextAddons custom editor",  "libraries", "ktextaddons"     >         "libtextcustomeditor"),
        kde!("KTextAddons text-to-speech", "libraries", "ktextaddons"     >         "libtextedittexttospeech"),
        kde!("KTextAddons emoticons",      "libraries", "ktextaddons"     >         "libtextemoticons"),
        kde!("KTextAddons grammar check",  "libraries", "ktextaddons"     >         "libtextgrammarcheck"),
        kde!("KTextAddons speech-to-text", "libraries", "ktextaddons"     >         "libtextspeechtotext"),
        kde!("KTextAddons translator",     "libraries", "ktextaddons"     >         "libtexttranslator"),
        kde!("KUnifiedPush",               "libraries"                    >         "kcm_push_notifications"),
        kde!("KWeatherCore",               "libraries"                    >         "kweathercore5"),
        kde!("KWebKitPart",                "libraries"),
        kde!("Perceptual Color",           "libraries", "perceptualcolor" > "poqm", "perceptualcolor-0_qt"),
        kde!("Phonon",                     "libraries"                    > "poqm", "libphonon_qt"),
        kde!("Phonon settings",            "libraries", "phonon"          > "poqm", "phononsettings_qt"),
        kde!("Phonon VLC",                 "libraries", "phonon-vlc"      > "poqm", "phonon_vlc_qt"),
        kde!("Snorenotify",                "libraries"                    > "poqm", "snorenotify-qt5_qt"),

        gnome!("Accerciser",              "accerciser"),
        gnome!("Baobab",                  "baobab"),
        gnome!("Calls",                   "calls"),
        gnome!("Cheese",                  "cheese"),
        gnome!("Connections",             "connections"),
        gnome!("Console",                 "console"),
        gnome!("Dconf Editor",            "dconf-editor"),
        gnome!("Devhelp",                 "devhelp"),
        gnome!("Endeavour",      "World", "Endeavour"),
        gnome!("Eye of GNOME",            "eog"),
        gnome!("Epiphany",                "epiphany"),
        gnome!("Evince",                  "evince"),
        gnome!("Evolution",               "evolution"),
        gnome!("File Roller",             "file-roller"),
        gnome!("Five or more",            "five-or-more"),
        gnome!("Four-in-a-row",           "four-in-a-row"),
        gnome!("GNOME Display Manager",   "gdm"),
        gnome!("gedit",                   "gedit"),
        gnome!("GHex",                    "ghex"),
        gnome!("Glade",                   "glade"),
        gnome!("Books",                   "gnome-books"),
        gnome!("Boxes",                   "gnome-boxes"),
        gnome!("Builder",                 "gnome-builder"),
        gnome!("Calculator",              "gnome-calculator"),
        gnome!("Calendar",                "gnome-calendar"),
        gnome!("Characters",              "gnome-characters"),
        gnome!("Chess",                   "gnome-chess"),
        gnome!("Clocks",                  "gnome-clocks"),
        gnome!("Color Manager",           "gnome-color-manager"),
        gnome!("Contacts",                "gnome-contacts"),
        gnome!("Settings",                "gnome-control-center"),
        gnome!("Disks",                   "gnome-disk-utility"),
        gnome!("Documents",               "gnome-documents"),
        gnome!("Font",                    "gnome-font-viewer"),
        gnome!("Keyring",                 "gnome-keyring"),
        gnome!("Klotski",                 "gnome-klotski"),
        gnome!("Logs",                    "gnome-logs"),
        gnome!("Mahjongg",                "gnome-mahjongg"),
        gnome!("Maps",                    "gnome-maps"),
        gnome!("menus",                   "gnome-menus"),
        gnome!("Mines",                   "gnome-mines"),
        gnome!("MultiWriter",             "gnome-multi-writer"),
        gnome!("Music",                   "gnome-music"),
        gnome!("Nettool",                 "gnome-nettool"),
        gnome!("Nibbles",                 "gnome-nibbles"),
        gnome!("Photos",                  "gnome-photos"),
        gnome!("Robots",                  "gnome-robots"),
        gnome!("Screenshot",              "gnome-screenshot"),
        gnome!("session manager",         "gnome-session"),
        gnome!("Settings Daemon",         "gnome-settings-daemon"),
        gnome!("Shell Extensions",        "gnome-shell-extensions"),
        gnome!("Shell",                   "gnome-shell"),
        gnome!("Software",                "gnome-software"),
        gnome!("Sudoku",                  "gnome-sudoku"),
        gnome!("System Monitor",          "gnome-system-monitor"),
        gnome!("Taquin",                  "gnome-taquin"),
        gnome!("Terminal",                "gnome-terminal"),
        gnome!("Tetravex",                "gnome-tetravex"),
        gnome!("Extra Themes",            "gnome-themes-extra"),
        gnome!("Tweaks",                  "gnome-tweaks"),
        gnome!("Usage",                   "gnome-usage"),
        gnome!("user share",              "gnome-user-share"),
        gnome!("Video Effects",           "gnome-video-effects"),
        gnome!("Weather",                 "gnome-weather"),
        gnome!("Grilo",                   "grilo"),
        gnome!("Grilo plugins",           "grilo-plugins"),
        gnome!("GVfs",                    "gvfs"),
        gnome!("Hitori",                  "hitori"),
        gnome!("Iagno",                   "iagno"),
        gnome!("Lights Off",              "lightsoff"),
        gnome!("Mutter",                  "mutter"),
        gnome!("Files",                   "nautilus"),
        gnome!("Orca",                    "orca"),
        gnome!("Polari",                  "polari"),
        gnome!("Quadrapassel",            "quadrapassel"),
        gnome!("Recipes",                 "recipes"),
        gnome!("Rygel",                   "rygel"),
        gnome!("Document Scanner",        "simple-scan"),
        gnome!("Sushi",                   "sushi"),
        gnome!("Swell Foop",              "swell-foop"),
        gnome!("Tali",                    "tali"),
        gnome!("Videos",                  "totem"),
        gnome!("Tracker Miners",          "tracker-miners"),
        gnome!("Tracker",                 "tracker"),
        gnome!("Vino",                    "vino"),
        gnome!("Sound Recorder", "World", "vocalis"),
        gnome!("xdg-user-dirs-gtk",       "xdg-user-dirs-gtk"),
        gnome!("Yelp",                    "yelp"),

        android!("", "bootable/recovery",                         "tools/recovery_l10n/res"),
        android!("", "development",                               "apps/Fallback/res"),
        android!("", "device/generic/vulkan-cereal",              "third-party/angle/src/android_system_settings/res"),
        android!("", "device/google/atv",                         "FrameworkPackageStubs/res"),
        android!("", "device/google/atv",                         "libraries/BluetoothServices/res"),
        android!("", "device/google/atv",                         "overlay/TvFrameworkOverlay/res"),
        android!("", "device/google/gs101",                       "overlay-vendor/vendor/google/apps/SetupWizard/res"),
        android!("", "frameworks/base",                           "core/res/res"),
        android!("", "frameworks/base",                           "libs/WindowManager/Shell/res"),
        android!("", "frameworks/base",                           "packages/BackupRestoreConfirmation/res"),
        android!("", "frameworks/base",                           "packages/CarrierDefaultApp/res"),
        android!("", "frameworks/base",                           "packages/CompanionDeviceManager/res"),
        android!("", "frameworks/base",                           "packages/DynamicSystemInstallationService/res"),
        android!("", "frameworks/base",                           "packages/ExternalStorageProvider/res"),
        android!("", "frameworks/base",                           "packages/FusedLocation/res"),
        android!("", "frameworks/base",                           "packages/InputDevices/res"),
        android!("", "frameworks/base",                           "packages/PackageInstaller/res"),
        android!("", "frameworks/base",                           "packages/PrintSpooler/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/BannerMessagePreference/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/FooterPreference/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/HelpUtils/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/RestrictedLockUtils/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/SearchWidget/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/SelectorWithWidgetPreference/res"),
        android!("", "frameworks/base",                           "packages/SettingsLib/res"),
        android!("", "frameworks/base",                           "packages/SettingsProvider/res"),
        android!("", "frameworks/base",                           "packages/Shell/res"),
        android!("", "frameworks/base",                           "packages/SimAppDialog/res"),
        android!("", "frameworks/base",                           "packages/SoundPicker/res"),
        android!("", "frameworks/base",                           "packages/SystemUI/res-keyguard"),
        android!("", "frameworks/base",                           "packages/SystemUI/res-product"),
        android!("", "frameworks/base",                           "packages/SystemUI/res"),
        android!("", "frameworks/base",                           "packages/VpnDialogs/res"),
        android!("", "frameworks/base",                           "packages/WallpaperCropper/res"),
        android!("", "frameworks/base",                           "packages/overlays/AvoidAppsInCutoutOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationCornerOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationDoubleOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationHoleOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationNarrowOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationTallOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationWaterfallOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/DisplayCutoutEmulationWideOverlay/res"),
        android!("", "frameworks/base",                           "packages/overlays/NoCutoutOverlay/res"),
        android!("", "frameworks/opt/chips",                      "res"),
        android!("", "frameworks/opt/chips",                      "sample/res"),
        android!("", "frameworks/opt/colorpicker",                "res"),
        android!("", "frameworks/opt/net/wifi",                   "libs/WifiTrackerLib/res"),
        android!("", "frameworks/opt/photoviewer",                "res"),
        android!("", "frameworks/opt/photoviewer",                "sample/res"),
        android!("", "frameworks/opt/setupwizard",                "library/main/res"),
        android!("", "frameworks/opt/timezonepicker",             "res"),
        android!("", "packages/apps/BasicSmsReceiver",            "res"),
        android!("", "packages/apps/Calendar",                    "res"),
        android!("", "packages/apps/Camera2",                     "res"),
        android!("", "packages/apps/Car/Calendar",                "res"),
        android!("", "packages/apps/Car/Launcher",                "res"),
        android!("", "packages/apps/Car/LinkViewer",              "res"),
        android!("", "packages/apps/Car/Notification",            "res"),
        android!("", "packages/apps/Car/Settings",                "res"),
        android!("", "packages/apps/Car/SystemUI",                "res"),
        android!("", "packages/apps/Car/SystemUpdater",           "res"),
        android!("", "packages/apps/Car/systemlibs",              "car-assist-client-lib/res"),
        android!("", "packages/apps/Car/systemlibs",              "car-broadcastradio-support/res"),
        android!("", "packages/apps/CellBroadcastReceiver",       "res"),
        android!("", "packages/apps/CertInstaller",               "res"),
        android!("", "packages/apps/Contacts",                    "res"),
        android!("", "packages/apps/DeskClock",                   "res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/about/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/app/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/assisteddialing/ui/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/blocking/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/blockreportspam/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/callcomposer/cameraui/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/callcomposer/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/calldetails/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/calllog/ui/menu/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/calllog/ui/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/calllogutils/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/clipboard/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/common/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/contactphoto/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/dialpadview/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/glidephotomanager/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/historyitemactions/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/interactions/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/main/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/notification/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/phonenumberutil/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/postcall/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/precall/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/preferredsim/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/preferredsim/suggestion/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/promotion/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/searchfragment/cp2/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/searchfragment/directories/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/searchfragment/list/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/searchfragment/nearbyplaces/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/shortcuts/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/spam/promo/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/spannable/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/speeddial/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/theme/common/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/util/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/voicemail/listui/error/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/voicemail/settings/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/dialer/widget/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/answer/impl/answermethod/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/answer/impl/hint/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/answer/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/audioroute/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/commontheme/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/contactgrid/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/disconnectdialog/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/hold/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/incall/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/rtt/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/sessiondata/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/spam/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/telecomeventui/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/theme/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/incallui/video/impl/res"),
        android!("", "packages/apps/Dialer",                      "java/com/android/voicemail/impl/res"),
        android!("", "packages/apps/DocumentsUI",                 "res"),
        android!("", "packages/apps/EmergencyInfo",               "EmergencyGestureAction/res"),
        android!("", "packages/apps/EmergencyInfo",               "res"),
        android!("", "packages/apps/Gallery",                     "res"),
        android!("", "packages/apps/Gallery2",                    "res"),
        android!("", "packages/apps/HTMLViewer",                  "res"),
        android!("", "packages/apps/KeyChain",                    "res"),
        android!("", "packages/apps/Launcher3",                   "go/quickstep/res"),
        android!("", "packages/apps/Launcher3",                   "quickstep/res"),
        android!("", "packages/apps/Launcher3",                   "res"),
        android!("", "packages/apps/LegacyCamera",                "res"),
        android!("", "packages/apps/ManagedProvisioning",         "res"),
        android!("", "packages/apps/Messaging",                   "res"),
        android!("", "packages/apps/Music",                       "kotlin/res"),
        android!("", "packages/apps/MusicFX",                     "res"),
        android!("", "packages/apps/Nfc",                         "res"),
        android!("", "packages/apps/PhoneCommon",                 "res"),
        android!("", "packages/apps/Protips",                     "res"),
        android!("", "packages/apps/QuickAccessWallet",           "res"),
        android!("", "packages/apps/SafetyRegulatoryInfo",        "res"),
        android!("", "packages/apps/Settings",                    "res"),
        android!("", "packages/apps/SettingsIntelligence",        "res"),
        android!("", "packages/apps/Stk",                         "res"),
        android!("", "packages/apps/StorageManager",              "res"),
        android!("", "packages/apps/TV",                          "common/res"),
        android!("", "packages/apps/TV",                          "res"),
        android!("", "packages/apps/Tag",                         "res"),
        android!("", "packages/apps/ThemePicker",                 "res"),
        android!("", "packages/apps/Traceur",                     "res"),
        android!("", "packages/apps/TvSettings",                  "Settings/res-twopanel"),
        android!("", "packages/apps/TvSettings",                  "Settings/res"),
        android!("", "packages/apps/TvSettings",                  "TwoPanelSettingsLib/res"),
        android!("", "packages/apps/WallpaperPicker",             "res"),
        android!("", "packages/apps/WallpaperPicker2",            "res"),
        android!("", "packages/inputmethods/LatinIME",            "java/res"),
        android!("", "packages/inputmethods/LeanbackIME",         "res"),
        android!("", "packages/modules/Bluetooth",                "android/app/res"),
        android!("", "packages/modules/CaptivePortalLogin",       "res"),
        android!("", "packages/modules/CellBroadcastService",     "res"),
        android!("", "packages/modules/Connectivity",             "Tethering/res"),
        android!("", "packages/modules/Connectivity",             "nearby/halfsheet/res"),
        android!("", "packages/modules/Connectivity",             "service/ServiceConnectivityResources/res"),
        android!("", "packages/modules/ExtServices",              "java/res"),
        android!("", "packages/modules/NetworkStack",             "res"),
        android!("", "packages/modules/Permission",               "PermissionController/res"),
        android!("", "packages/modules/Permission",               "SafetyCenter/Resources/res"),
        android!("", "packages/modules/Wifi",                     "OsuLogin/res"),
        android!("", "packages/modules/Wifi",                     "service/ServiceWifiResources/res"),
        android!("", "packages/providers/BlockedNumberProvider",  "res"),
        android!("", "packages/providers/CalendarProvider",       "res"),
        android!("", "packages/providers/ContactsProvider",       "res"),
        android!("", "packages/providers/DownloadProvider",       "res"),
        android!("", "packages/providers/DownloadProvider",       "ui/res"),
        android!("", "packages/providers/MediaProvider",          "res"),
        android!("", "packages/providers/TelephonyProvider",      "res"),
        android!("", "packages/providers/TvProvider",             "res"),
        android!("", "packages/providers/UserDictionaryProvider", "res"),
        android!("", "packages/screensavers/Basic",               "res"),
        android!("", "packages/screensavers/PhotoTable",          "res"),
        android!("", "packages/services/BuiltInPrintService",     "res"),
        android!("", "packages/services/Car",                     "FrameworkPackageStubs/res"),
        android!("", "packages/services/Car",                     "car-admin-ui-lib/src/main/res"),
        android!("", "packages/services/Car",                     "car-maps-placeholder/res"),
        android!("", "packages/services/Car",                     "car-usb-handler/res"),
        android!("", "packages/services/Car",                     "car_product/car_ui_portrait/apps/CarUiPortraitSystemUI/res"),
        android!("", "packages/services/Car",                     "car_product/car_ui_portrait/rro/CarEvsCameraPreviewAppRRO/res"),
        android!("", "packages/services/Car",                     "car_product/car_ui_portrait/rro/CarUiPortraitDialerRRO/res"),
        android!("", "packages/services/Car",                     "car_product/car_ui_portrait/rro/CarUiPortraitLauncherRRO/res"),
        android!("", "packages/services/Car",                     "car_product/car_ui_portrait/rro/CarUiPortraitNotificationRRO/res"),
        android!("", "packages/services/Car",                     "car_product/overlay/frameworks/base/core/res/res"),
        android!("", "packages/services/Car",                     "experimental/service/res"),
        android!("", "packages/services/Car",                     "packages/CarDeveloperOptions/res"),
        android!("", "packages/services/Car",                     "packages/CarManagedProvisioning/res"),
        android!("", "packages/services/Car",                     "service-builtin/res"),
        android!("", "packages/services/Car",                     "service/res"),
        android!("", "packages/services/Car",                     "tests/BugReportApp/res"),
        android!("", "packages/services/Car",                     "tests/DiagnosticTools/res"),
        android!("", "packages/services/Car",                     "tests/MultiDisplaySecondaryHomeTestLauncher/res"),
        android!("", "packages/services/Car",                     "tests/MultiDisplayTest/res"),
        android!("", "packages/services/Car",                     "tests/MultiDisplayTestHelloActivity/res"),
        android!("", "packages/services/Mtp",                     "res"),
        android!("", "packages/services/Telecomm",                "res"),
        android!("", "packages/services/Telephony",               "res"),
        android!("", "packages/services/Telephony",               "testapps/GbaTestApp/res"),
        android!("", "packages/services/Telephony",               "testapps/TestSliceApp/app/src/main/res"),
        android!("", "packages/wallpapers/LivePicker",            "res"),
    ];

    #[cfg(debug_assertions)]
    {
        let mut set = HashSet::with_capacity(providers.len());
        for provider in &providers {
            if let Some(group_name) = provider.group_name() {
                set.insert(group_name);
            }
        }
        for (i, provider) in providers.iter().enumerate() {
            if set.contains(provider.id()) {
                panic!("Duplicate id: {}, second at index {i}", provider.id());
            }
            // if set.contains(provider.name()) {
            //     panic!("Duplicate name: {}, second at index {i}", provider.name());
            // }
            // set.insert(provider.name());
        }
    }

    providers
}
